[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrettyPrint = "8162dcfd-2161-5ef2-ae6c-7681170c5f98"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DataStructures = "0.19.1"
Distributions = "0.25.120"
IterTools = "1.10.0"
LinearAlgebra = "1.11.0"
PrettyPrint = "0.2.0"
Random = "1.11.0"
Statistics = "1.11.1"
